name: 'kafka'
version: 0.1.0
description: Kafka Client library for Dartlang
homepage: https://github.com/pulyaevskiy/dart-kafka
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  quiver: ^3.2.1
  logging: ^1.1.0

dev_dependencies:
  test: ^1.22.2
  mockito: ^5.3.2
  build_runner: ^2.3.3
  # dart_coveralls: "^0.4.0"
